apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: caching-redis
spec:
  anonymousAuth: false
  certIssuer: self-signed-ca
  certIssuerType: ClusterIssuer
  nodes: 3
  servicePassword:
    key: password
    name: caching-redis
    optional: false
  # tls: true
