apiVersion: batch/v1
kind: CronJob
metadata:
  name: housekeeping
  labels:
    app.kubernetes.io/component: housekeeping
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 5
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: housekeeping
        spec:
          automountServiceAccountToken: false
          containers:
            - name: netbox-housekeeping
              command:
                - /opt/netbox/venv/bin/python
                - /opt/netbox/netbox/manage.py
                - housekeeping
              image: ghcr.io/netbox-community/netbox:v4.3.2
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                seLinuxOptions: {}
                type: "RuntimeDefault"
              volumeMounts:
                - name: config
                  mountPath: /etc/netbox/config/configuration.py
                  subPath: configuration.py
                  readOnly: true
                # - name: config
                #   mountPath: /etc/netbox/config/ldap/ldap_config.py
                #   subPath: ldap_config.py
                #   readOnly: true
                - name: config
                  mountPath: /run/config/netbox
                  readOnly: true
                - name: media
                  mountPath: /opt/netbox/netbox/media
                - name: netbox-tmp
                  mountPath: /tmp
                - name: reports
                  mountPath: /opt/netbox/netbox/reports
                - name: secrets
                  mountPath: /run/secrets/netbox
                  readOnly: true
          restartPolicy: OnFailure
          serviceAccountName: netbox
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: Always
            supplementalGroups: []
            sysctls: []
          volumes:
            - name: config
              configMap:
                name: netbox
            - name: media
              persistentVolumeClaim:
                claimName: netbox-media
            - name: netbox-tmp
              emptyDir:
                medium: Memory
            # - name: reports
            #   persistentVolumeClaim:
            #     claimName: netbox-reports
            - name: scripts
              persistentVolumeClaim:
                claimName: netbox-scripts
            - name: secrets
              projected:
                sources:
                  - secret:
                      name: caching-redis
                      items:
                        - key: redis-password
                          path: redis_cache_password
                  - secret:
                      name: netbox-config
                      items:
                        - key: email_password
                          path: email_password
                        # - key: ldap_bind_password
                        #   path: ldap_bind_password
                        - key: secret_key
                          path: secret_key
                  - secret:
                      name: postgresql-user
                      items:
                        - key: password
                          path: db_password
                  - secret:
                      name: tasks-redis
                      items:
                        - key: redis-password
                          path: redis_tasks_password
