apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: netbox-config

commonLabels:
  app: netbox
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: netbox-config

namespace: netbox

resources:
  - httproute.yaml
  - namespace.yaml
  - postgresql-certificate.yaml
  - postgresql-cluster.yaml
  - postgresql-superuser-secret.yaml
  - postgresql-tls-secret.yaml
  - postgresql-user-secret.yaml
