apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudnative-pg-config

commonLabels:
  app: cloudnative-pg
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: cloudnative-pg-config

resources:
  - httproute.yaml
  - namespace.yaml
  - netbox-postgresql-secret.yaml
  - postgresql-cluster.yaml
  - postgresql-superuser-secret.yaml
  - postgresql-user-secret.yaml
