apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netbox
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
