apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbox
spec:
  # ingressClassName: ""
  pathType: ImplementationSpecific
  # tls:
  #   - hosts:
  #     - host: chart-example.local
  #       paths:
  #         - /
  #     secretName: {{ .secretName }}
  rules:
  - host: netbox.local
    http:
      paths:
        - path: /*
          pathType: Prefix
          backend: netbox
