apiVersion: v1
kind: Secret
metadata:
  name: netbox-config
  annotations:
    custom.argocd.argoproj.io/ignore-path: ".data"
type: Opaque
data:
  email_password: ""
  # ldap_bind_password: ""
  secret_key: ""
