apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-postgresql
  namespace: netbox
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-bookworm
  instances: 1
  storage:
    size: 128i
