apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: netbox
spec:
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
      secret:
        name: netbox-postgresql-user
  certificates:
    serverCASecret: postgresql-tls
    serverTLSSecret: postgresql-tls
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-bookworm
  instances: 1
  storage:
    size: 128Mi
  superuserSecret:
    name: netbox-postgresql-superuser
